server:
  port: 8080
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/RUHungry?useSSL=false&serverTimezone=UTC
      username: root
      password: zxl010128

logging:
  level:
    root: info
    org.example.mapper: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: true
    db-config:
      id-type: AUTO
      field-strategy: IGNORED
